extends:
  - airbnb
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
parser: babel-eslint
env:
  browser: true
rules:
  strict: 0
  no-console: 1
  arrow-parens:
    - 2
    - as-needed
  'import/extensions':
    - 0
  flow-vars/define-flow-type: 1
  flow-vars/use-flow-type: 1
plugins:
  - flow-vars
