extends:
  - airbnb
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
parser: babel-eslint
plugins:
- flow-vars
env:
  browser: true
  # this can be removed after extracting renderer into another repo
  jest: true
rules:
  strict: 0
  no-console: 1
  arrow-parens:
    - 2
    - as-needed
  'import/extensions':
    - 0
  flow-vars/define-flow-type: 1
  flow-vars/use-flow-type: 1
overrides:
  -
    files:
      - "test/**"
    rules:
      "import/no-extraneous-dependencies":
        - 0
  -
    files:
      - "server.js"
    rules:
      "no-console":
        - 0
