extends:
  - airbnb
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
plugins:
  - '@typescript-eslint'
env:
  browser: true
  # this can be removed after extracting renderer into another repo
rules:
  no-console: 0
  arrow-parens:
    - 2
    - as-needed
  'import/extensions':
    - 0
  no-plusplus:
    - 0 # Airbnb's justification curiosly appears to only be applicable when you are not also
        # requiring semicolons, even though they do
  object-curly-newline:
    - 2
    - consistent: true # disagreeing with Airbnb
  no-underscore-dangle:
    - 0 # defaulting to opinionlessness
  consistent-return:
    - 0 # this rule insists, for example, that callbacks passed to forEach must 'return undefined'
  no-param-reassign:
    - 0 # we're currently using mutation in some places, but we could revise to avoid this
  arrow-body-style:
    - 0 # tries to ban multiline arrow functions
  'react/jsx-filename-extension':
    - 2
    - extensions:
      - '.js'
      - '.jsx'
      - '.ts'
      - '.tsx'
  'no-use-before-define':
    - 0 # yields error about React being imported too late in .tsx files
  '@typescript-eslint/no-use-before-define':
    - 2
  '@typescript-eslint/ban-ts-comment':
    - 0 # there exist non-trivial typing errors
  'prefer-destructuring':
    - 0 # sometimes impossible because of typing
overrides:
  -
    files:
      - 'web/server.js'
    rules:
      'no-console':
       - 0
  -
    files:
      - 'src/editor-core/epics/**'
    rules:
      '@typescript-eslint/explicit-module-boundary-types':
        - 0 # better to just infer these
settings:
  'import/resolver':
    node:
      extensions:
        - '.js'
        - '.jsx'
        - '.ts'
        - '.tsx'
