extends:
  - airbnb
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:flowtype/recommended
parser: babel-eslint
plugins:
  - flowtype
env:
  browser: true
  # this can be removed after extracting renderer into another repo
  jest: true
rules:
  strict: 0
  no-console: 1
  arrow-parens:
    - 2
    - as-needed
  'import/extensions':
    - 0
  no-undef:
    # despite the flowtype plugin, this excepts various flowtyping
    - 0
overrides:
  -
    files:
      - "test/**"
    rules:
      "import/no-extraneous-dependencies":
        - 0
  -
    files:
      - "server.js"
    rules:
      "no-console":
        - 0
